export loadInfo from './loadInfo';
export loadAuth from './loadAuth';
export login from './login';
export logout from './logout';
export register from './register';
export user from './user';
export print from './print';
export press from './press';
export addPress from './addPress';
export printed from './printed';
export upload from './upload';
export copon from './copon';
export makeCopon from './makeCopon';
export * as widget from './widget/index';
